# =============================================================================
# 02_SBD_SPEED.R
# Chapter 1: Camera Trap Density Estimation
# =============================================================================
#
# PURPOSE: Calculate movement speeds using Size-Biased Distribution (SBD)
#          following Rowcliffe et al. 2016 methodology.
#
# METHOD:  SBD uses the harmonic mean to correct for size-biased sampling
#          (faster animals are more likely to be detected by cameras).
#
# FIXES (Feb 2026):
#   1. Sort by filename frame number within sequences, not timestamp.
#      All frames in sequence 9486720 share timestamp 16:37 -- sorting by
#      timestamp gives arbitrary order, wildly inflating path distance.
#      Filename (IMG_0330, IMG_0332...) encodes true capture order.
#
#   2. Zero-duration sequences excluded entirely.
#      If first and last frame share the same timestamp, duration = 0 and
#      speed is undefined. Previously these were estimated from frame rate
#      which is not defensible. Now excluded from SBD.
#
#   3. Tortuosity filter: sequences with path/straight-line > 3 excluded.
#      Tortuosity > 3 is biologically implausible within a single sequence
#      and indicates coordinate noise accumulating above anchoring threshold.
#      Diagnostic confirmed 37-50% of sequences for some species exceed
#      this threshold, with mean tortuosity up to 250 for Mule Deer.
#
# INPUT:   01_data_for_speed.csv from Step 1
# OUTPUT:  SBD speed estimates by species
#
# =============================================================================

# Load configuration
source("00_config.R")

library(tidyverse)
library(lubridate)

cat("\n")
cat("=============================================================\n")
cat("STEP 02: SBD SPEED ESTIMATION\n")
cat("Rowcliffe et al. 2016 Methodology\n")
cat("With Species-Specific Anchoring\n")
cat("=============================================================\n\n")

# =============================================================================
# 1. LOAD CLEAN DATA
# =============================================================================

cat("Loading clean data from Step 1...\n")

input_file <- paste0(OUTPUT_DIRS$processed, "01_data_for_speed.csv")
data <- read.csv(input_file, stringsAsFactors = FALSE)

# Parse timestamp
data$timestamp_clean <- as.POSIXct(data$timestamp_clean, tz = "UTC")

cat("  - Loaded", nrow(data), "records\n")
cat("  - Sequences:", n_distinct(data$sequence_id_use), "\n")
cat("  - Species:", n_distinct(data$common_name_clean), "\n\n")

# =============================================================================
# 2. SORT BY FILENAME FRAME NUMBER
#
#    FIX: Many sequences have multiple frames sharing the same timestamp
#    (camera captures several frames within one second). Sorting by timestamp
#    alone produces arbitrary ordering within those ties, causing the path
#    distance calculation to jump between positions non-chronologically.
#    Filenames (IMG_0330, IMG_0332...) encode the true capture order.
#    Extract the numeric part of the filename and sort by that instead.
# =============================================================================

cat("Sorting frames by filename order within sequences...\n")

data <- data %>%
  mutate(
    frame_number = as.numeric(str_extract(filename, "\\d+"))
  ) %>%
  arrange(sequence_id_use, frame_number)

# Verify sort worked
n_missing_frame_num <- sum(is.na(data$frame_number))
if(n_missing_frame_num > 0) {
  cat("  WARNING:", n_missing_frame_num, "frames could not extract frame number from filename\n")
  cat("  These will sort after numbered frames within their sequence\n")
  cat("  Check filename format if this number is large\n")
} else {
  cat("  Frame numbers extracted successfully from all filenames\n")
}
cat("\n")

# =============================================================================
# 3. LOAD SPECIES-SPECIFIC ANCHORING THRESHOLDS
#
#    Thresholds are read from proposed_thresholds.csv, which is generated by
#    02a_anchor_sweep.R and edited by the user before running this script.
#    If the file does not exist, hardcoded defaults are used as fallback.
# =============================================================================

cat("Loading species-specific anchoring and tortuosity thresholds...\n")

thresholds_file <- paste0(OUTPUT_DIRS$tables, "proposed_thresholds.csv")

if(file.exists(thresholds_file)) {
  thresholds_df <- read.csv(thresholds_file, stringsAsFactors = FALSE) %>%
    select(common_name_clean, final_threshold, tortuosity_threshold)
  cat("  Read thresholds from proposed_thresholds.csv\n")
  cat("  (edit that file and re-run to change thresholds)\n\n")
} else {
  cat("  WARNING: proposed_thresholds.csv not found -- using hardcoded defaults\n")
  cat("  Run 02a_anchor_sweep.R to generate empirical thresholds\n\n")
  thresholds_df <- data.frame(
    common_name_clean = c(
      "White-tailed Deer", "Mule Deer", "Elk", "Moose",
      "American Black Bear", "Puma", "Coyote", "Bobcat", "Red Fox", "Grey Wolf",
      "Wild Turkey",
      "Red Squirrel", "Snowshoe Hare", "Eastern Chipmunk", "Eastern Cottontail",
      "Northern Raccoon", "Columbian Ground Squirrel", "Eastern Gray Squirrel",
      "Eastern Fox Squirrel", "Douglas's Squirrel", "Northern Flying Squirrel"
    ),
    final_threshold = c(
      0.5, 0.5, 0.5, 0.5,
      0.3, 0.3, 0.3, 0.3, 0.3, 0.3,
      0.2,
      0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1
    ),
    tortuosity_threshold = c(
      3, 3, 3, 3,
      3, 3, 3, 3, 3, 3,
      3,
      5, 5, 5, 5, 5, 5, 5, 5, 5, 5
    )
  )
}

# Apply thresholds -- species not in file get anchor 0.2, tortuosity 3
data <- data %>%
  left_join(thresholds_df, by = "common_name_clean") %>%
  mutate(
    anchoring_threshold  = ifelse(is.na(final_threshold), 0.2, final_threshold),
    tortuosity_threshold = ifelse(is.na(tortuosity_threshold), 3, tortuosity_threshold)
  ) %>%
  select(-final_threshold)

# Report thresholds
cat("=== ANCHORING THRESHOLDS BY SPECIES ===\n")
data %>%
  group_by(common_name_clean, anchoring_threshold) %>%
  summarise(n_detections = n(), .groups = "drop") %>%
  arrange(desc(n_detections)) %>%
  print(n = 20)
cat("\n")

# =============================================================================
# 4. COLLAPSE TO ONE COORDINATE PER UNIQUE TIMESTAMP
#
#    Problem: burst sequences have many frames sharing the same timestamp.
#    Calculating distances across all of them accumulates per-frame coordinate
#    noise as fake movement -- small steps between burst frames add up to
#    meters of inflated path distance even when the animal barely moved.
#
#    Fix: keep only the FIRST frame at each unique timestamp within each
#    sequence. Path distance is then calculated between second-level positions
#    only. For a sequence with 2 unique timestamps, path = straight-line.
#    Duration (last_timestamp - first_timestamp) is unchanged.
# =============================================================================

cat("Collapsing to first frame per unique timestamp within each sequence...\n")

n_frames_before <- nrow(data)

data_collapsed <- data %>%
  group_by(sequence_id_use, timestamp_clean) %>%
  slice(1) %>%
  ungroup()

n_frames_after   <- nrow(data_collapsed)
n_frames_dropped <- n_frames_before - n_frames_after

cat("  Frames before collapse:", n_frames_before, "\n")
cat("  Frames after collapse: ", n_frames_after,  "\n")
cat("  Burst frames dropped:  ", n_frames_dropped,
    "(", round(100 * n_frames_dropped / n_frames_before, 1), "%)\n\n")

data_collapsed %>%
  group_by(common_name_clean) %>%
  summarise(
    n_timestamps            = n(),
    n_sequences             = n_distinct(sequence_id_use),
    mean_timestamps_per_seq = round(n_timestamps / n_sequences, 1),
    .groups = "drop"
  ) %>%
  arrange(desc(n_timestamps)) %>%
  { cat("Timestamps per sequence after collapse:\n"); . } %>%
  print(n = 15)

cat("\n")

# =============================================================================
# 5. EDGE FRAME FILTER
#
#    Problem: AI depth estimation is unreliable when the animal's bounding box
#    is at the edge of the frame -- the box is partially clipped and the depth
#    model produces inflated or erratic world_z values. This can happen at any
#    point in a sequence, not just the first/last frame.
#
#    Fix: flag any collapsed point where the bounding box touches the left or
#    right edge of the frame (xmin < EDGE_FRACTION or xmax > 1-EDGE_FRACTION).
#    For sequences with at least one non-edge point, compute the median world_z
#    of the non-edge points as a reference. Drop any edge-flagged point whose
#    world_z exceeds EDGE_Z_MULTIPLIER x that reference median.
#
#    Only-edge sequences (every point is on the edge) are left unchanged since
#    there is no non-edge reference to compare against.
# =============================================================================

EDGE_FRACTION    <- 1/6   # matches 04_staying_time.R edge definition
EDGE_Z_MULTIPLIER <- 1.5  # drop edge point if world_z > this x non-edge median

cat("Applying edge frame filter (bounding-box based)...\n")

# Flag any point where bounding box touches left or right edge
data_collapsed <- data_collapsed %>%
  mutate(
    is_edge_frame = (!is.na(xmin) & xmin < EDGE_FRACTION) |
      (!is.na(xmax) & xmax > (1 - EDGE_FRACTION))
  )

# Compute median world_z of non-edge points per sequence
non_edge_medians <- data_collapsed %>%
  filter(!is_edge_frame) %>%
  group_by(sequence_id_use) %>%
  summarise(non_edge_median_z = median(world_z, na.rm = TRUE), .groups = "drop")

data_collapsed <- data_collapsed %>%
  left_join(non_edge_medians, by = "sequence_id_use") %>%
  mutate(
    # Drop edge frames whose depth exceeds 2x the non-edge median
    # Leave edge frames alone if there is no non-edge reference
    edge_outlier = is_edge_frame &
      !is.na(non_edge_median_z) &
      world_z > EDGE_Z_MULTIPLIER * non_edge_median_z
  )

n_edge_flagged  <- sum(data_collapsed$is_edge_frame, na.rm = TRUE)
n_edge_dropped  <- sum(data_collapsed$edge_outlier, na.rm = TRUE)
n_seqs_affected <- data_collapsed %>%
  filter(edge_outlier) %>%
  distinct(sequence_id_use) %>%
  nrow()

cat("  Edge fraction threshold:", round(EDGE_FRACTION, 3), "(left xmin or right xmax)\n")
cat("  Edge-flagged points:    ", n_edge_flagged, "\n")
cat("  Edge outliers dropped:  ", n_edge_dropped, "\n")
cat("  Sequences affected:     ", n_seqs_affected, "\n\n")

# Edge filter summary by species
data_collapsed %>%
  group_by(common_name_clean) %>%
  summarise(
    n_edge_flagged  = sum(is_edge_frame, na.rm = TRUE),
    n_edge_dropped  = sum(edge_outlier, na.rm = TRUE),
    pct_dropped     = round(100 * n_edge_dropped / max(n_edge_flagged, 1), 1),
    .groups = "drop"
  ) %>%
  filter(n_edge_flagged > 0) %>%
  arrange(desc(n_edge_flagged)) %>%
  { cat("Edge points dropped by species:\n"); . } %>%
  print(n = 15)

cat("\n")

# Remove edge outliers
data_collapsed <- data_collapsed %>%
  filter(!edge_outlier) %>%
  select(-is_edge_frame, -non_edge_median_z, -edge_outlier)

# =============================================================================
# 6. CALCULATE STEP-TO-STEP MOVEMENTS WITH ANCHORING
#    (operating on collapsed, edge-filtered coordinates)
# =============================================================================

cat("Calculating step-to-step movements with species-specific anchoring...\n")

data_speed <- data_collapsed %>%
  group_by(sequence_id_use) %>%
  mutate(
    frame_num    = row_number(),
    n_frames_seq = n(),
    
    prev_x    = lag(world_x),
    prev_z    = lag(world_z),
    prev_time = lag(timestamp_clean),
    
    # Step distance (meters) - raw
    frame_distance_raw = sqrt((world_x - prev_x)^2 + (world_z - prev_z)^2),
    
    # Apply species-specific anchoring
    frame_distance = ifelse(frame_distance_raw < anchoring_threshold,
                            0,
                            frame_distance_raw),
    
    # Step time -- always > 0 after collapse since timestamps are unique
    frame_time = as.numeric(difftime(timestamp_clean, prev_time, units = "secs")),
    
    frame_speed = ifelse(frame_time > 0, frame_distance / frame_time, NA_real_)
  ) %>%
  ungroup()

cat("  - Calculated movements for", sum(!is.na(data_speed$frame_distance)), "steps\n")

# Report anchoring by species
anchoring_summary <- data_speed %>%
  filter(!is.na(frame_distance_raw)) %>%
  group_by(common_name_clean, anchoring_threshold) %>%
  summarise(
    n_frames = n(),
    n_anchored = sum(frame_distance_raw < anchoring_threshold & 
                       frame_distance_raw > 0, na.rm = TRUE),
    pct_anchored = round(100 * n_anchored / n_frames, 1),
    .groups = "drop"
  ) %>%
  arrange(desc(n_frames))

cat("\n=== ANCHORING SUMMARY BY SPECIES ===\n")
print(anchoring_summary, n = 20)
cat("\n")

# =============================================================================
# 5. CALCULATE SEQUENCE-LEVEL SPEEDS
# =============================================================================

cat("Calculating sequence-level speeds...\n")

sequence_speeds <- data_speed %>%
  group_by(sequence_id_use, deployment_id_clean, common_name_clean, anchoring_threshold) %>%
  summarise(
    n_frames = n(),
    
    # Time span -- using real timestamps
    start_time    = min(timestamp_clean, na.rm = TRUE),
    end_time      = max(timestamp_clean, na.rm = TRUE),
    duration_secs = as.numeric(difftime(end_time, start_time, units = "secs")),
    
    # Path distance (sum of anchored frame-to-frame distances)
    path_distance = sum(frame_distance, na.rm = TRUE),
    
    # Straight-line distance (first to last frame in filename order)
    straight_distance = sqrt(
      (last(world_x) - first(world_x))^2 + 
        (last(world_z) - first(world_z))^2
    ),
    
    # Mean detection distance
    mean_detection_dist = mean(world_z, na.rm = TRUE),
    
    .groups = "drop"
  ) %>%
  mutate(
    # Sequence speed (path distance / real duration)
    sequence_speed = ifelse(duration_secs > 0, 
                            path_distance / duration_secs, 
                            NA_real_),
    
    # Tortuosity (path / straight-line)
    tortuosity = ifelse(straight_distance > 0, 
                        path_distance / straight_distance, 
                        NA_real_)
  )

cat("  - Calculated speeds for", nrow(sequence_speeds), "sequences\n\n")

# =============================================================================
# 6. APPLY SEQUENCE-LEVEL FILTERS
#
#    Filter 1 -- Zero-duration: exclude sequences where first and last frame
#    share the same timestamp. Speed is undefined (duration = 0). These are
#    entire sequences captured within one second -- cannot estimate real speed.
#    NOTE: zero-duration here means the real timestamp span is 0, not an
#    estimated-from-frame-rate duration.
#
#    Filter 2 -- Tortuosity: exclude sequences with path/straight-line > 3.
#    Biologically, no animal travels a path 3x longer than its net displacement
#    within a single short sequence. Values above this are coordinate noise
#    accumulating above the anchoring threshold. Diagnostic confirmed mean
#    tortuosity of 250 for Mule Deer and 25 for White-tailed Deer -- clear
#    noise contamination driving inflated SBD estimates.
#
#    Filter 3 -- Minimum frames and positive speed (existing filters).
# =============================================================================

cat("=============================================================\n")
cat("SEQUENCE FILTERING\n")
cat("=============================================================\n\n")

n_total     <- nrow(sequence_speeds)
n_zero_dur  <- sum(sequence_speeds$duration_secs == 0, na.rm = TRUE)
n_too_few   <- sum(sequence_speeds$n_frames < SBD_CONFIG$min_frames)
n_zero_spd  <- sum(sequence_speeds$sequence_speed == 0 |
                     is.na(sequence_speeds$sequence_speed) |
                     !is.finite(sequence_speeds$sequence_speed), na.rm = TRUE)

# Tortuosity removals are per-species so report them after the join
cat("  Total sequences:                    ", n_total, "\n")
cat("  Excluded - zero duration:           ", n_zero_dur,
    "(", round(100 * n_zero_dur / n_total, 1), "%)\n")
cat("  Excluded - fewer than", SBD_CONFIG$min_frames, "frames:    ", n_too_few,
    "(", round(100 * n_too_few / n_total, 1), "%)\n")
cat("  Excluded - zero/invalid speed:      ", n_zero_spd,
    "(", round(100 * n_zero_spd / n_total, 1), "%)\n")
cat("  (tortuosity exclusions reported per-species below)\n\n")

sequence_speeds_valid <- sequence_speeds %>%
  left_join(
    data %>% distinct(sequence_id_use, tortuosity_threshold),
    by = "sequence_id_use"
  ) %>%
  mutate(tortuosity_threshold = ifelse(is.na(tortuosity_threshold),
                                       SBD_CONFIG$max_tortuosity,
                                       tortuosity_threshold)) %>%
  filter(
    duration_secs > 0,                                    # real duration required
    tortuosity <= tortuosity_threshold | is.na(tortuosity), # per-species tortuosity cap
    n_frames >= SBD_CONFIG$min_frames,
    sequence_speed > 0,
    is.finite(sequence_speed)
  )

cat("Sequences remaining after all filters:", nrow(sequence_speeds_valid),
    "(", round(100 * nrow(sequence_speeds_valid) / n_total, 1), "% of total)\n\n")

# Per-species tortuosity filter summary
cat("Tortuosity filter summary by species:\n")
sequence_speeds %>%
  left_join(
    data %>% distinct(sequence_id_use, tortuosity_threshold),
    by = "sequence_id_use"
  ) %>%
  mutate(tortuosity_threshold = ifelse(is.na(tortuosity_threshold),
                                       SBD_CONFIG$max_tortuosity,
                                       tortuosity_threshold)) %>%
  filter(duration_secs > 0, n_frames >= SBD_CONFIG$min_frames,
         sequence_speed > 0, is.finite(sequence_speed)) %>%
  group_by(common_name_clean, tortuosity_threshold) %>%
  summarise(
    n_total    = n(),
    n_removed  = sum(tortuosity > tortuosity_threshold, na.rm = TRUE),
    pct_removed = round(100 * n_removed / n_total, 1),
    n_retained  = n_total - n_removed,
    .groups = "drop"
  ) %>%
  arrange(desc(n_total)) %>%
  print(n = 15)

cat("\n")

# =============================================================================
# 7. SBD CALCULATION FUNCTION
# =============================================================================

calculate_sbd <- function(speeds, min_n = 10, n_boot = 1000) {
  # Remove invalid values and zeros (Rowcliffe: speed when moving)
  speeds <- speeds[!is.na(speeds) & is.finite(speeds) & speeds > 0]
  
  if(length(speeds) < min_n) {
    return(data.frame(
      n = length(speeds),
      sbd_mean = NA,
      sbd_se = NA,
      sbd_lcl = NA,
      sbd_ucl = NA,
      arithmetic_mean = NA,
      median = NA
    ))
  }
  
  # Harmonic mean (SBD estimator)
  harmonic_mean <- 1 / mean(1 / speeds)
  
  # Bootstrap for SE and CI
  boot_results <- replicate(n_boot, {
    boot_sample <- sample(speeds, replace = TRUE)
    1 / mean(1 / boot_sample)
  })
  
  data.frame(
    n = length(speeds),
    sbd_mean = harmonic_mean,
    sbd_se = sd(boot_results),
    sbd_lcl = quantile(boot_results, 0.025),
    sbd_ucl = quantile(boot_results, 0.975),
    arithmetic_mean = mean(speeds),
    median = median(speeds)
  )
}

# =============================================================================
# 8. CALCULATE SBD BY SPECIES
# =============================================================================

cat("Calculating SBD speeds by species...\n")

sbd_results <- sequence_speeds_valid %>%
  group_by(common_name_clean) %>%
  group_modify(~ calculate_sbd(.x$sequence_speed, 
                               min_n = THRESHOLDS$min_sbd_n,
                               n_boot = SBD_CONFIG$bootstrap_reps)) %>%
  ungroup() %>%
  arrange(desc(n))

# Add anchoring threshold to results
species_thresholds <- data %>%
  group_by(common_name_clean) %>%
  summarise(anchoring_threshold = first(anchoring_threshold), .groups = "drop")

sbd_results <- sbd_results %>%
  left_join(species_thresholds, by = "common_name_clean")

cat("\n=== SBD SPEED RESULTS ===\n")
print(sbd_results %>% 
        select(common_name_clean, anchoring_threshold, n, sbd_mean, 
               sbd_se, sbd_lcl, sbd_ucl), 
      n = 20)

# =============================================================================
# 9. SUMMARY STATISTICS
# =============================================================================

cat("\n=============================================================\n")
cat("SBD SPEED SUMMARY\n")
cat("=============================================================\n")
cat("Filters applied:\n")
cat("  - Filename-order sort (fixes same-second frame ordering)\n")
cat("  - Zero-duration sequences excluded\n")
cat("  - Per-species tortuosity filter (from proposed_thresholds.csv)\n")
cat("    default 3 for large/medium species, 5 for small mammals\n")
cat("  - Minimum", SBD_CONFIG$min_frames, "frames per sequence\n")
cat("  - Zeros excluded (Rowcliffe: speed when moving)\n\n")
cat("Species-specific anchoring thresholds:\n")
cat("  - Large ungulates (deer, elk, moose): 0.5m\n")
cat("  - Medium carnivores (bear, puma, coyote): 0.3m\n")
cat("  - Small mammals (squirrels, hares): 0.1m\n")
cat("  - Birds (turkey): 0.2m\n\n")
cat("Minimum sample size:", THRESHOLDS$min_sbd_n, "sequences\n")
cat("Bootstrap replicates:", SBD_CONFIG$bootstrap_reps, "\n")
cat("Species with valid estimates:", sum(!is.na(sbd_results$sbd_mean)), "\n")
cat("=============================================================\n\n")

# =============================================================================
# 10. SAVE RESULTS
# =============================================================================

cat("Saving results...\n")

# SBD results (PRIMARY OUTPUT)
output_sbd <- paste0(OUTPUT_DIRS$processed, "02_sbd_speeds.csv")
write.csv(sbd_results, output_sbd, row.names = FALSE)
cat("  - SBD speeds:", output_sbd, "\n")

# Sequence-level speeds (for diagnostics/figures)
output_seq <- paste0(OUTPUT_DIRS$processed, "02_sbd_sequence_speeds.csv")
write.csv(sequence_speeds_valid, output_seq, row.names = FALSE)
cat("  - Sequence-level:", output_seq, "\n")

# All sequences including excluded ones (for reporting filter effects)
output_seq_all <- paste0(OUTPUT_DIRS$processed, "02_sbd_sequence_speeds_all.csv")
write.csv(sequence_speeds, output_seq_all, row.names = FALSE)
cat("  - All sequences (pre-filter):", output_seq_all, "\n")

# Anchoring summary
output_anchor <- paste0(OUTPUT_DIRS$tables, "02_anchoring_summary.csv")
write.csv(anchoring_summary, output_anchor, row.names = FALSE)
cat("  - Anchoring summary:", output_anchor, "\n")

# Save as RDS for next scripts
output_rds <- paste0(OUTPUT_DIRS$processed, "02_sbd_results.rds")
saveRDS(list(
  sbd_results = sbd_results,
  sequence_speeds = sequence_speeds_valid,
  sequence_speeds_all = sequence_speeds,
  anchoring_thresholds = thresholds_df,
  anchoring_summary = anchoring_summary
), output_rds)
cat("  - All results (RDS):", output_rds, "\n")

cat("\n")
cat("=============================================================\n")
cat("STEP 02 COMPLETE\n")
cat("=============================================================\n")
cat("\nNext: Run 03_activity.R\n\n")

# =============================================================================
# OBJECTS AVAILABLE FOR NEXT SCRIPT
# =============================================================================
# sbd_results           - SBD speed estimates by species
# sequence_speeds_valid - Sequence-level speed data (post-filter)
# sequence_speeds       - All sequence-level data (pre-filter, for reporting)
# anchoring_summary     - How many frames anchored per species